version: '2'
services:
  influxdb:
    image: influxdb:1.0.1-alpine
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - "./data/influxdb:/var/lib/influxdb"
  grafana:
    image: grafana/grafana:3.1.1
    ports:
      - "3000:3000"
  locust:
    build: .
    ports:
      - "8089:8089"
    volumes:
      - ".:/srv/app"
    command: "locust -f /srv/app/locustfile.py --host http://grafana:3000"

